export { computeSlots } from './slot-engine';
export { type ComposedVisit, InvalidVisit, type VisitLine, composeVisit, isSingleService } from './visit';
export {
  CORRECTION_WINDOW_MS,
  type RescheduleDecision,
  type TransitionContext,
  type TransitionDecision,
  type TransitionRefusal,
  canReschedule,
  canTransition,
  isCorrection,
  possibleTransitionsFrom,
} from './transitions';
export {
  ACTIVE_STATUSES,
  APPOINTMENT_STATUSES,
  type AppointmentStatus,
  SLOT_FREEING_STATUSES,
  TERMINAL_STATUSES,
  activeStatusSqlList,
  occupiesTime,
  slotFreeingSqlList,
} from './status';
export {
  type BusyInterval,
  type CalendarDay,
  type Exclusion,
  type ExclusionReason,
  type Instant,
  InvalidSlotQuery,
  InvalidTimeValue,
  type Slot,
  type SlotLabel,
  type SlotPolicy,
  type SlotQuery,
  type SlotResult,
  type WallTime,
  type WorkingWindow,
  type ZoneId,
  calendarDay,
  instant,
  instantFromIso,
  wallTime,
  zoneId,
} from './types';
