/**
 * A-049 — STANDING APPOINTMENTS, AS A CALENDAR RULE (the pure half).
 *
 * "Every four weeks, same time" is the sentence a salon actually says, and it
 * is a rule on the CALENDAR axis (D-3): a weekday and a wall time, repeated.
 * It is emphatically NOT an instant plus a physical offset. Four weeks is
 * 2_419_200_000 milliseconds only when no clock changes in between; add that
 * to a 14:00 appointment across spring-forward and the client is told 15:00.
 *
 * So occurrences are generated by CALENDAR ARITHMETIC — `addDays` over
 * branded day strings, which cannot drift because nothing is ever converted —
 * and each resulting `(day, time)` pair is handed to the one conversion
 * module, once, at the end. Nothing here reads a clock or constructs a `Date`.
 *
 * THE PART THAT MATTERS: `resolve()` returns three arms, and a series is the
 * one feature in this product that hits all three in ordinary use. A
 * fortnightly 02:30 appointment meets a day where 02:30 does not exist. A
 * fortnightly 01:30 meets a day where it happens twice. Both are real weeks in
 * a real book, and this module refuses to pretend otherwise: it reports what
 * it found and lets the caller decide, which is the same shape D-26 gave the
 * column push and A-019 gave the bulk reassign.
 */
import { type CalendarDay, type Instant, type WallTime, type ZoneId, addDays, resolve } from '../time';

const DAYS_PER_WEEK = 7;

export interface SeriesRule {
  /** The first occurrence's calendar day — the anchor the rest count from. */
  anchorDay: CalendarDay;
  /** The wall time every occurrence is booked at. */
  time: WallTime;
  /** 1 = weekly, 2 = fortnightly, 4 = "every four weeks". */
  intervalWeeks: number;
  /** How many occurrences the desk asked for, anchor INCLUDED — "book her
   *  next six" means six appointments, not six more. */
  count: number;
}

/**
 * One planned occurrence, before anything is written.
 *
 * `at` is present exactly when the wall time resolves to a single instant.
 * The other two arms carry no `at` ON PURPOSE: a caller that wants to book a
 * gap occurrence has to look at `kind` first, and the type will not let it
 * skip that. Coercing a gap into "the nearest real time" is the defect spec
 * DST-8 names — luxon shifts forward, date-fns-tz shifts back, and both book a
 * time the client never chose.
 */
export type PlannedOccurrence =
  | { ordinal: number; day: CalendarDay; kind: 'unique'; at: Instant }
  | { ordinal: number; day: CalendarDay; kind: 'gap'; earlier: Instant; later: Instant }
  | {
      ordinal: number;
      day: CalendarDay;
      kind: 'ambiguous';
      /** Both are real, bookable, and an hour apart (spec FB-1/FB-4). */
      earlier: Instant;
      later: Instant;
    };

export class InvalidSeries extends Error {
  readonly field: string;
  constructor(field: string, message: string) {
    super(message);
    this.name = 'InvalidSeries';
    this.field = field;
  }
}

/**
 * The occurrences a rule plans, in order, anchor first.
 *
 * Pure: no clock, no `Date`, no database. Given the same rule and zone it
 * returns the same list forever, which is what makes the DST cases testable
 * against the spec's verified instants rather than against today's date.
 */
export function planOccurrences(rule: SeriesRule, zone: ZoneId): PlannedOccurrence[] {
  if (!Number.isInteger(rule.intervalWeeks) || rule.intervalWeeks < 1) {
    throw new InvalidSeries('intervalWeeks', 'Repeat every whole number of weeks, at least one.');
  }
  if (!Number.isInteger(rule.count) || rule.count < 1) {
    throw new InvalidSeries('count', 'A series needs at least one appointment.');
  }
  // A ceiling rather than a policy: the guard exists so a mistyped "600" is
  // refused at the form instead of writing six hundred rows into the book and
  // making somebody undo them by hand. The number is deliberately generous —
  // weekly for two years — because the salon's real limit is its own horizon.
  if (rule.count > 104) {
    throw new InvalidSeries('count', 'A series is capped at 104 appointments. Book the next stretch nearer the time.');
  }

  const occurrences: PlannedOccurrence[] = [];
  for (let ordinal = 0; ordinal < rule.count; ordinal++) {
    // CALENDAR arithmetic on a branded day string. `addDays` cannot cross the
    // axis because there is no instant here to be wrong about — which is the
    // entire reason the rule is stored as a day and a wall time rather than as
    // an instant and a duration.
    const day = addDays(rule.anchorDay, ordinal * rule.intervalWeeks * DAYS_PER_WEEK);
    const resolution = resolve(day, rule.time, zone);
    occurrences.push({ ordinal, day, ...resolution } as PlannedOccurrence);
  }
  return occurrences;
}

/**
 * The instant a planned occurrence should be booked at, or `null` when a human
 * has to decide.
 *
 * `ambiguous` takes the EARLIER of the two, and that is a reuse rather than a
 * new rule: `Business.ambiguousLocalTime` already has `offer-earlier-only` as
 * a supported policy, and the earlier instant is the one a person means by
 * "01:30" when asked. It is still reported as ambiguous by `planOccurrences`,
 * so the desk is told which week doubled rather than being quietly assigned a
 * side of it.
 *
 * `gap` returns null. There is no honest instant: the client's time genuinely
 * does not happen that week, and picking one for her is spec DST-8's defect.
 */
export function bookableInstant(occurrence: PlannedOccurrence): Instant | null {
  switch (occurrence.kind) {
    case 'unique':
      return occurrence.at;
    case 'ambiguous':
      return occurrence.earlier;
    case 'gap':
      return null;
  }
}
