export {
  type ClientNoteVersionSummary,
  type ClientSummary,
  type ClientVisit,
  type ContactMatch,
  MergeRefused,
  type MergeResult,
  type RebookSuggestion,
  type SaveNotesResult,
  type UpdateContactResult,
  clientHistory,
  findClient,
  findClientsByPhone,
  findReturningClient,
  findSplitRecords,
  latestClientNoteVersion,
  mergeClients,
  rebookSuggestion,
  saveClientNotes,
  searchClients,
  updateClientContact,
} from './clients';
export {
  type ClientReliability,
  type MissedAppointment,
  clientReliability,
  missedAppointments,
  reliabilityFor,
} from './reliability';
export {
  type CallMark,
  type CallMarkOutcome,
  clearCallMark,
  listCallMarks,
  recordCallMark,
} from './call-marks';
